# This workflow builds a Swift project using Tuist
# For more information see: https://tuist.io/docs

name: RunTest

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Install Tuist
    - name: Install Tuist
      run: |
        curl -Ls https://install.tuist.io | bash
        export PATH="$HOME/.tuist/bin:$PATH"

    # Generate Xcode project with Tuist
    - name: Generate Xcode Project
      run: |
        tuist fetch
        tuist generate --no-open

    # Build and test with Xcode
    - name: Build and Test
      run: |
        xcodebuild clean test \
        -project CobyHappiness.xcodeproj \
        -scheme CobyHappiness \
        -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
